---
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    standard:
      datefmt: '%H:%M:%S'
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    extended:
      datefmt: '%H:%M:%S'
      format: '%(levelname)-8s; %(asctime)s; %(name)s; %(module)s:%(funcName)s;%(lineno)d: %(message)s'
  handlers:
    console_handler:
      level: DEBUG
      formatter: extended
      class: 'logging.StreamHandler'
      stream: 'ext://sys.stdout'
    file_handler:
      level: DEBUG
      class: 'logging.FileHandler'
      formatter: extended
      filename: 'jobs/logs/smart_city_log.log'
      mode: a
      encoding: 'utf-8'
  loggers:
    main_smart_city: 
      level: DEBUG
      handlers:
      - console_handler
      - file_handler
...